/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author madar
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        posicionAlfil = new javax.swing.JLabel();
        filaAlfil = new javax.swing.JLabel();
        columnaAlfil = new javax.swing.JLabel();
        alfilIcon = new javax.swing.JLabel();
        txtFilaAlfil = new javax.swing.JTextField();
        txtColumnaAlfil = new javax.swing.JTextField();
        txtColumnaPeon = new javax.swing.JTextField();
        posicionPeon = new javax.swing.JLabel();
        filaPeon = new javax.swing.JLabel();
        columnaPeon = new javax.swing.JLabel();
        peonIcon = new javax.swing.JLabel();
        txtFilaPeon = new javax.swing.JTextField();
        direccion = new javax.swing.JLabel();
        boxDireccion = new javax.swing.JComboBox<>();
        btnJugar = new javax.swing.JButton();
        btnPdf = new javax.swing.JButton();
        presentacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Juego del Alfil");

        posicionAlfil.setText("Posición:");

        filaAlfil.setText("Fila:");

        columnaAlfil.setText("Columna:");

        alfilIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Alfil.png"))); // NOI18N

        txtFilaAlfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFilaAlfilActionPerformed(evt);
            }
        });

        posicionPeon.setText("Posición:");

        filaPeon.setText("Fila:");

        columnaPeon.setText("Columna:");

        peonIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Peon.png"))); // NOI18N

        txtFilaPeon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFilaPeonActionPerformed(evt);
            }
        });

        direccion.setText("Dirección:");

        boxDireccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ir hacia abajo", "Ir hacia arriba" }));

        btnJugar.setText("Jugar !!!");

        btnPdf.setText("IMPRIMIR PDF");
        btnPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPdfActionPerformed(evt);
            }
        });

        presentacion.setText("Proyecto realizado por CRISTIAN CAMARGO 1151595 y YILBER PATIÑO 1151509");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnJugar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(alfilIcon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(posicionAlfil)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(columnaAlfil)
                                            .addComponent(filaAlfil))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtFilaAlfil, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                            .addComponent(txtColumnaAlfil))))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(peonIcon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(posicionPeon)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(columnaPeon)
                                            .addComponent(filaPeon))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtFilaPeon)
                                            .addComponent(txtColumnaPeon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(boxDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(direccion)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(btnPdf))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(presentacion)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(posicionPeon)
                            .addComponent(direccion))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(filaPeon)
                            .addComponent(txtFilaPeon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(columnaPeon)
                            .addComponent(txtColumnaPeon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(peonIcon)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(posicionAlfil)
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(filaAlfil)
                            .addComponent(txtFilaAlfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(columnaAlfil)
                            .addComponent(txtColumnaAlfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(alfilIcon))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJugar)
                    .addComponent(btnPdf))
                .addGap(18, 18, 18)
                .addComponent(presentacion)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFilaAlfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFilaAlfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFilaAlfilActionPerformed

    private void txtFilaPeonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFilaPeonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFilaPeonActionPerformed

    private void btnPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPdfActionPerformed
        
    }//GEN-LAST:event_btnPdfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alfilIcon;
    public javax.swing.JComboBox<String> boxDireccion;
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnPdf;
    private javax.swing.JLabel columnaAlfil;
    private javax.swing.JLabel columnaPeon;
    private javax.swing.JLabel direccion;
    private javax.swing.JLabel filaAlfil;
    private javax.swing.JLabel filaPeon;
    private javax.swing.JLabel peonIcon;
    private javax.swing.JLabel posicionAlfil;
    private javax.swing.JLabel posicionPeon;
    private javax.swing.JLabel presentacion;
    public javax.swing.JTextField txtColumnaAlfil;
    public javax.swing.JTextField txtColumnaPeon;
    public javax.swing.JTextField txtFilaAlfil;
    public javax.swing.JTextField txtFilaPeon;
    // End of variables declaration//GEN-END:variables
}
