/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author madar
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
//        ImageIcon imgAlfil = new ImageIcon(getClass().getResource("/imagenes/Alfil.png"));
//        ImageIcon imgPeon = new ImageIcon(getClass().getResource("/imagenes/Peon.png"));
//
//        Icon fondoAlfil = new ImageIcon(imgAlfil.getImage().getScaledInstance(alfilIcon.getWidth(), alfilIcon.getHeight(), Image.SCALE_DEFAULT));
//        alfilIcon.setIcon(fondoAlfil);
//
//        Icon fondoPeon = new ImageIcon(imgPeon.getImage().getScaledInstance(peonIcon.getWidth(), peonIcon.getHeight(), Image.SCALE_DEFAULT));
//        peonIcon.setIcon(fondoAlfil);
//        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        posicionAlfil = new javax.swing.JLabel();
        filaAlfil = new javax.swing.JLabel();
        columnaAlfil = new javax.swing.JLabel();
        txtFilaAlfil = new javax.swing.JTextField();
        txtColumnaAlfil = new javax.swing.JTextField();
        txtColumnaPeon = new javax.swing.JTextField();
        posicionPeon = new javax.swing.JLabel();
        filaPeon = new javax.swing.JLabel();
        columnaPeon = new javax.swing.JLabel();
        txtFilaPeon = new javax.swing.JTextField();
        direccion = new javax.swing.JLabel();
        boxDireccion = new javax.swing.JComboBox<>();
        btnJugar = new javax.swing.JButton();
        btnPdf = new javax.swing.JButton();
        presentacion = new javax.swing.JLabel();
        peonIcon = new javax.swing.JLabel();
        alfilIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Juego del Alfil");

        posicionAlfil.setText("Posición:");

        filaAlfil.setText("Fila:");

        columnaAlfil.setText("Columna:");

        txtFilaAlfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFilaAlfilActionPerformed(evt);
            }
        });

        posicionPeon.setText("Posición:");

        filaPeon.setText("Fila:");

        columnaPeon.setText("Columna:");

        txtFilaPeon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFilaPeonActionPerformed(evt);
            }
        });

        direccion.setText("Dirección:");

        boxDireccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ir hacia abajo", "Ir hacia arriba" }));
        boxDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxDireccionActionPerformed(evt);
            }
        });

        btnJugar.setText("Jugar !!!");

        btnPdf.setText("IMPRIMIR PDF");
        btnPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPdfActionPerformed(evt);
            }
        });

        presentacion.setText("Proyecto realizado por CRISTIAN CAMARGO 1151595 y YILBER PATIÑO 1151509");

        peonIcon.setText("      PEON");
        peonIcon.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        alfilIcon.setText("       ALFIL");
        alfilIcon.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alfilIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(columnaAlfil)
                    .addComponent(filaAlfil)
                    .addComponent(posicionAlfil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFilaAlfil)
                    .addComponent(txtColumnaAlfil, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(peonIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(posicionPeon)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(columnaPeon)
                            .addComponent(filaPeon))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFilaPeon)
                            .addComponent(txtColumnaPeon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnPdf))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boxDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direccion))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(presentacion)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btnJugar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(posicionAlfil)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(filaAlfil)
                            .addComponent(txtFilaAlfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(columnaAlfil)
                            .addComponent(txtColumnaAlfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(peonIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alfilIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(posicionPeon)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(filaPeon)
                                    .addComponent(txtFilaPeon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(direccion)
                                .addGap(23, 23, 23)
                                .addComponent(boxDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(columnaPeon)
                            .addComponent(txtColumnaPeon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJugar)
                    .addComponent(btnPdf))
                .addGap(32, 32, 32)
                .addComponent(presentacion)
                .addGap(75, 75, 75))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFilaAlfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFilaAlfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFilaAlfilActionPerformed

    private void txtFilaPeonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFilaPeonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFilaPeonActionPerformed

    private void btnPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPdfActionPerformed

    }//GEN-LAST:event_btnPdfActionPerformed

    private void boxDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxDireccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alfilIcon;
    public javax.swing.JComboBox<String> boxDireccion;
    public javax.swing.JButton btnJugar;
    public javax.swing.JButton btnPdf;
    private javax.swing.JLabel columnaAlfil;
    private javax.swing.JLabel columnaPeon;
    private javax.swing.JLabel direccion;
    private javax.swing.JLabel filaAlfil;
    private javax.swing.JLabel filaPeon;
    private javax.swing.JLabel peonIcon;
    private javax.swing.JLabel posicionAlfil;
    private javax.swing.JLabel posicionPeon;
    private javax.swing.JLabel presentacion;
    public javax.swing.JTextField txtColumnaAlfil;
    public javax.swing.JTextField txtColumnaPeon;
    public javax.swing.JTextField txtFilaAlfil;
    public javax.swing.JTextField txtFilaPeon;
    // End of variables declaration//GEN-END:variables
}
